spring:
  application:
    name: taco-cloud
  thymeleaf:
    cache: false

  datasource:
    generate-unique-name: false
    name: tacocloud
    username: stepan
    password: 1234
    url: jdbc:h2:mem:tacocloud

  data:
    jdbc:
      dialect: h2
    rest:
      base-path: /api

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

taco:
  props:
    orderPageSize: 20
    tacoPageSize: 20

security:
  props:
    ignore-csrf-url-patterns: /**